# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=30)),
                ('shou', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=6)),
                ('phone', models.CharField(default='', max_length=11)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
